spring:
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username: demo
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  web:
    resources:
      chain:
        compressed: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
mybatis:
  mapper-locations: classpath:**/*Mapper.xml
  type-aliases-super-type: java.io.Serializable
  type-aliases-package: com.github.bestheroz
  config-location: classpath:mybatis-config.xml
server:
  compression:
    enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID_DEMO
    encoding:
      charset: UTF-8
      enabled: true
      force: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /
  paths-to-match:
    - /api/v1/**
decorator:
  datasource:
    p6spy:
      logging: slf4j
      multiline: true
