name: Test

on: push

jobs:
  gradle:
    name: test gradle
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 8 ]

    steps:
      - uses: actions/checkout@main

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@main
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: wrapper
          arguments: |
            build
            --no-daemon
            --exclude-task test
            -Dspring.profiles.active=dev

      - uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: always()
