package com.github.bestheroz.demo.api.code;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CodeApiDescription {
  public final String GET_ITEMS =
      "```\n"
          + "SELECT\n"
          + "    `updated_by`,\n"
          + "    `created_by`,\n"
          + "    `created`,\n"
          + "    `available`,\n"
          + "    `display_order`,\n"
          + "    `id`,\n"
          + "    `text`,\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `updated`\n"
          + "FROM\n"
          + "    `code`\n"
          + "```";

  public final String GET_ITEMS_ORDER_BY =
      "```\n"
          + "SELECT\n"
          + "    `updated_by`,\n"
          + "    `created_by`,\n"
          + "    `created`,\n"
          + "    `available`,\n"
          + "    `display_order`,\n"
          + "    `id`,\n"
          + "    `text`,\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `updated`\n"
          + "FROM\n"
          + "    `code`\n"
          + "ORDER BY\n"
          + "    `display_order` desc\n"
          + "```";

  public final String GET_ITEMS_BY_MAP =
      "```\n"
          + "SELECT\n"
          + "    `updated_by`,\n"
          + "    `created_by`,\n"
          + "    `created`,\n"
          + "    `available`,\n"
          + "    `display_order`,\n"
          + "    `id`,\n"
          + "    `text`,\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `updated`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "    )\n"
          + "```";
  public final String GET_ITEMS_BY_MAP_ORDER_BY =
      "```\n"
          + "SELECT\n"
          + "    `updated_by`,\n"
          + "    `created_by`,\n"
          + "    `created`,\n"
          + "    `available`,\n"
          + "    `display_order`,\n"
          + "    `id`,\n"
          + "    `text`,\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `updated`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "    )\n"
          + "ORDER BY\n"
          + "    `display_order` desc\n"
          + "```";

  public final String GET_ITEM_BY_ID =
      "```\n"
          + "SELECT\n"
          + "    `updated_by`,\n"
          + "    `created_by`,\n"
          + "    `created`,\n"
          + "    `available`,\n"
          + "    `display_order`,\n"
          + "    `id`,\n"
          + "    `text`,\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `updated`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `id` = 3\n"
          + "    )\n"
          + "```";

  public final String GET_ITEM_BY_MAP =
      "```\n"
          + "SELECT\n"
          + "    `updated_by`,\n"
          + "    `created_by`,\n"
          + "    `created`,\n"
          + "    `available`,\n"
          + "    `display_order`,\n"
          + "    `id`,\n"
          + "    `text`,\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `updated`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "        AND `value` = 'E2'\n"
          + "    )\n"
          + "```";

  public final String GET_TARGET_ITEMS =
      "```\n"
          + "SELECT\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `text`\n"
          + "FROM\n"
          + "    `code`\n"
          + "```";

  public final String GET_TARGET_ITEMS_ORDER_BY =
      "```\n"
          + "SELECT\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `text`,\n"
          + "    `display_order`\n"
          + "FROM\n"
          + "    `code`\n"
          + "ORDER BY\n"
          + "    `display_order` desc\n"
          + "```";
  public final String GET_TARGET_ITEMS_BY_MAP =
      "```\n"
          + "SELECT\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `text`,\n"
          + "    `display_order`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "    )\n"
          + "```";

  public final String GET_TARGET_ITEMS_BY_MAP_ORDER_BY =
      "```\n"
          + "SELECT\n"
          + "    `type`,\n"
          + "    `value`,\n"
          + "    `text`,\n"
          + "    `display_order`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "    )\n"
          + "ORDER BY\n"
          + "    `display_order` desc\n"
          + "```";
  public final String COUNT_ALL =
      "```\n" + "SELECT\n" + "    COUNT(1) AS CNT\n" + "FROM\n" + "    `code`\n" + "```";
  public final String COUNT_BY_MAP =
      "```\n"
          + "SELECT\n"
          + "    COUNT(1) AS CNT\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "    )\n"
          + "```";
  public final String GET_DISTINCT_ITEMS =
      "```\n"
          + "SELECT\n"
          + "    DISTINCT `type`, `available`\n"
          + "FROM\n"
          + "    `code`\n"
          + "```";
  public final String GET_DISTINCT_ITEMS_ORDER_BY =
      "```SELECT\n"
          + "    DISTINCT `type`, `available`\n"
          + "FROM\n"
          + "    `code`\n"
          + "ORDER BY\n"
          + "    `display_order` desc\n"
          + "```";
  public final String GET_DISTINCT_ITEMS_BY_MAP =
      "```\n"
          + "SELECT\n"
          + "    DISTINCT `type`, `available`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "    )\n"
          + "```";
  public final String GET_DISTINCT_ITEMS_BY_MAP_ORDER_BY =
      "```\n"
          + "SELECT\n"
          + "    DISTINCT `type`, `available`\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `type` = 'EXAMPLE'\n"
          + "    )\n"
          + "ORDER BY\n"
          + "    `display_order` desc\n"
          + "```";
  public final String INSERT =
      "```\n"
          + "INSERT\n"
          + "INTO\n"
          + "    `code`  (\n"
          + "        `available`, `display_order`, `id`, `text`, `type`, `value`, `CREATED`, `UPDATED`, `CREATED_BY`, `UPDATED_BY`\n"
          + "    )\n"
          + "VALUES\n"
          + "    (false, 20, null, '예제3', 'EXAMPLE', 'E3', NOW(), NOW(), 1004, 1004)\n"
          + "```";
  public final String INSERT_BATCH =
      "```\n"
          + "INSERT\n"
          + "INTO\n"
          + "    `code`  (\n"
          + "        `updated_by`, `created_by`, `created`, `available`, `display_order`, `id`, `text`, `type`, `value`, `updated`\n"
          + "    )\n"
          + "VALUES\n"
          + "    (1004, 1004, NOW(), true, 10, null, '샘플5', 'SAMPLE', 'S5', NOW()),\n"
          + "    (1004, 1004, NOW(), true, 11, null, '샘플6', 'SAMPLE', 'S6', NOW()),\n"
          + "    (1004, 1004, NOW(), true, 12, null, '샘플7', 'SAMPLE', 'S7', NOW())\n"
          + "```";
  public final String UPDATE_BY_ID =
      "```\n"
          + "UPDATE\n"
          + "    `code`\n"
          + "SET\n"
          + "    `available` = false,\n"
          + "    `display_order` = 20,\n"
          + "    `id` = null,\n"
          + "    `text` = '예제3',\n"
          + "    `type` = 'EXAMPLE',\n"
          + "    `value` = 'E3',\n"
          + "    `UPDATED` = NOW(),\n"
          + "    `UPDATED_BY` = '1004'\n"
          + "WHERE\n"
          + "    (\n"
          + "        `id` = 4\n"
          + "    )\n"
          + "```";

  public final String UPDATE_BY_MAP =
      "```\n"
          + "UPDATE\n"
          + "    `code`\n"
          + "SET\n"
          + "    `available` = false,\n"
          + "    `display_order` = 20,\n"
          + "    `id` = null,\n"
          + "    `text` = '예제3',\n"
          + "    `type` = 'EXAMPLE',\n"
          + "    `value` = 'E3',\n"
          + "    `UPDATED` = NOW(),\n"
          + "    `UPDATED_BY` = '1004'\n"
          + "WHERE\n"
          + "    (\n"
          + "        `display_order` = 3\n"
          + "    )\n"
          + "```";
  public final String UPDATE_MAP_BY_MAP =
      "```\n"
          + "UPDATE\n"
          + "    `code`\n"
          + "SET\n"
          + "    `text` = '예제3',\n"
          + "    `UPDATED` = NOW(),\n"
          + "    `UPDATED_BY` = '1004'\n"
          + "WHERE\n"
          + "    (\n"
          + "        `display_order` = 3\n"
          + "    )\n"
          + "```";
  public final String UPDATE_MAP_BY_ID =
      "```\n"
          + "UPDATE\n"
          + "    `code`\n"
          + "SET\n"
          + "    `text` = '예제3',\n"
          + "    `UPDATED` = NOW(),\n"
          + "    `UPDATED_BY` = '1004'\n"
          + "WHERE\n"
          + "    (\n"
          + "        `id` = 5\n"
          + "    )\n"
          + "```";
  public final String DELETE_BY_ID =
      "```\n"
          + "DELETE\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `id` = 5\n"
          + "    )\n"
          + "```";
  public final String DELETE_BY_MAP =
      "```\n"
          + "DELETE\n"
          + "FROM\n"
          + "    `code`\n"
          + "WHERE\n"
          + "    (\n"
          + "        `display_order` = 3\n"
          + "    )\n"
          + "```";
}
